name: Tests
on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          '3.8',
          '3.9',
          '3.10',
        ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.1.4
    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install libsodium-dev libsecp256k1-dev libgmp-dev -y
    - name: Install project
      run: make install
    - name: Run lint
      run: make lint
    - name: Run tests
      run: make test
