name: Test
on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "Makefile"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          3.8,
          3.9,
          3.10,
        ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.2.0"

      - name: Set up cache
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install libsodium-dev libsecp256k1-dev libgmp-dev -y

      - name: Install project
        run: make install
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make test
